package com.sandbox.order.order;

/** An order about to be inserted with status CREATED; identifiers are generated by the caller. */
public record NewOrder(String orderId, String partnerOrderId, String customerName, String phone, long amount,
		OrderMode mode, String correlationId, String partnerTransactionId) {

}
